// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.5
// source: shortener_v2.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchShortenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Urls          []*BatchURLItem        `protobuf:"bytes,2,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchShortenRequest) Reset() {
	*x = BatchShortenRequest{}
	mi := &file_shortener_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchShortenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchShortenRequest) ProtoMessage() {}

func (x *BatchShortenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchShortenRequest.ProtoReflect.Descriptor instead.
func (*BatchShortenRequest) Descriptor() ([]byte, []int) {
	return file_shortener_v2_proto_rawDescGZIP(), []int{0}
}

func (x *BatchShortenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BatchShortenRequest) GetUrls() []*BatchURLItem {
	if x != nil {
		return x.Urls
	}
	return nil
}

type BatchURLItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchURLItem) Reset() {
	*x = BatchURLItem{}
	mi := &file_shortener_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchURLItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchURLItem) ProtoMessage() {}

func (x *BatchURLItem) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchURLItem.ProtoReflect.Descriptor instead.
func (*BatchURLItem) Descriptor() ([]byte, []int) {
	return file_shortener_v2_proto_rawDescGZIP(), []int{1}
}

func (x *BatchURLItem) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchURLItem) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type BatchShortenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BatchShortenResult  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchShortenResponse) Reset() {
	*x = BatchShortenResponse{}
	mi := &file_shortener_v2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchShortenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchShortenResponse) ProtoMessage() {}

func (x *BatchShortenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchShortenResponse.ProtoReflect.Descriptor instead.
func (*BatchShortenResponse) Descriptor() ([]byte, []int) {
	return file_shortener_v2_proto_rawDescGZIP(), []int{2}
}

func (x *BatchShortenResponse) GetItems() []*BatchShortenResult {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatchShortenResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchShortenResult) Reset() {
	*x = BatchShortenResult{}
	mi := &file_shortener_v2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchShortenResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchShortenResult) ProtoMessage() {}

func (x *BatchShortenResult) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchShortenResult.ProtoReflect.Descriptor instead.
func (*BatchShortenResult) Descriptor() ([]byte, []int) {
	return file_shortener_v2_proto_rawDescGZIP(), []int{3}
}

func (x *BatchShortenResult) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchShortenResult) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type ShortenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenRequest) Reset() {
	*x = ShortenRequest{}
	mi := &file_shortener_v2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenRequest) ProtoMessage() {}

func (x *ShortenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenRequest.ProtoReflect.Descriptor instead.
func (*ShortenRequest) Descriptor() ([]byte, []int) {
	return file_shortener_v2_proto_rawDescGZIP(), []int{4}
}

func (x *ShortenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ShortenRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ShortenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenResponse) Reset() {
	*x = ShortenResponse{}
	mi := &file_shortener_v2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenResponse) ProtoMessage() {}

func (x *ShortenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenResponse.ProtoReflect.Descriptor instead.
func (*ShortenResponse) Descriptor() ([]byte, []int) {
	return file_shortener_v2_proto_rawDescGZIP(), []int{5}
}

func (x *ShortenResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type ResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_shortener_v2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_shortener_v2_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveRequest) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type ResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_shortener_v2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_shortener_v2_proto_rawDescGZIP(), []int{7}
}

func (x *ResolveResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

var File_shortener_v2_proto protoreflect.FileDescriptor

const file_shortener_v2_proto_rawDesc = "" +
	"\n" +
	"\x12shortener_v2.proto\x12\fshortener.v2\"^\n" +
	"\x13BatchShortenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12.\n" +
	"\x04urls\x18\x02 \x03(\v2\x1a.shortener.v2.BatchURLItemR\x04urls\"X\n" +
	"\fBatchURLItem\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"N\n" +
	"\x14BatchShortenResponse\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .shortener.v2.BatchShortenResultR\x05items\"X\n" +
	"\x12BatchShortenResult\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\";\n" +
	"\x0eShortenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\".\n" +
	"\x0fShortenResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\"-\n" +
	"\x0eResolveRequest\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\"4\n" +
	"\x0fResolveResponse\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl2\xf9\x01\n" +
	"\x10ShortenerService\x12F\n" +
	"\aShorten\x12\x1c.shortener.v2.ShortenRequest\x1a\x1d.shortener.v2.ShortenResponse\x12F\n" +
	"\aResolve\x12\x1c.shortener.v2.ResolveRequest\x1a\x1d.shortener.v2.ResolveResponse\x12U\n" +
	"\fBatchShorten\x12!.shortener.v2.BatchShortenRequest\x1a\".shortener.v2.BatchShortenResponseB\x03Z\x01.b\x06proto3"

var (
	file_shortener_v2_proto_rawDescOnce sync.Once
	file_shortener_v2_proto_rawDescData []byte
)

func file_shortener_v2_proto_rawDescGZIP() []byte {
	file_shortener_v2_proto_rawDescOnce.Do(func() {
		file_shortener_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shortener_v2_proto_rawDesc), len(file_shortener_v2_proto_rawDesc)))
	})
	return file_shortener_v2_proto_rawDescData
}

var file_shortener_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_shortener_v2_proto_goTypes = []any{
	(*BatchShortenRequest)(nil),  // 0: shortener.v2.BatchShortenRequest
	(*BatchURLItem)(nil),         // 1: shortener.v2.BatchURLItem
	(*BatchShortenResponse)(nil), // 2: shortener.v2.BatchShortenResponse
	(*BatchShortenResult)(nil),   // 3: shortener.v2.BatchShortenResult
	(*ShortenRequest)(nil),       // 4: shortener.v2.ShortenRequest
	(*ShortenResponse)(nil),      // 5: shortener.v2.ShortenResponse
	(*ResolveRequest)(nil),       // 6: shortener.v2.ResolveRequest
	(*ResolveResponse)(nil),      // 7: shortener.v2.ResolveResponse
}
var file_shortener_v2_proto_depIdxs = []int32{
	1, // 0: shortener.v2.BatchShortenRequest.urls:type_name -> shortener.v2.BatchURLItem
	3, // 1: shortener.v2.BatchShortenResponse.items:type_name -> shortener.v2.BatchShortenResult
	4, // 2: shortener.v2.ShortenerService.Shorten:input_type -> shortener.v2.ShortenRequest
	6, // 3: shortener.v2.ShortenerService.Resolve:input_type -> shortener.v2.ResolveRequest
	0, // 4: shortener.v2.ShortenerService.BatchShorten:input_type -> shortener.v2.BatchShortenRequest
	5, // 5: shortener.v2.ShortenerService.Shorten:output_type -> shortener.v2.ShortenResponse
	7, // 6: shortener.v2.ShortenerService.Resolve:output_type -> shortener.v2.ResolveResponse
	2, // 7: shortener.v2.ShortenerService.BatchShorten:output_type -> shortener.v2.BatchShortenResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shortener_v2_proto_init() }
func file_shortener_v2_proto_init() {
	if File_shortener_v2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shortener_v2_proto_rawDesc), len(file_shortener_v2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shortener_v2_proto_goTypes,
		DependencyIndexes: file_shortener_v2_proto_depIdxs,
		MessageInfos:      file_shortener_v2_proto_msgTypes,
	}.Build()
	File_shortener_v2_proto = out.File
	file_shortener_v2_proto_goTypes = nil
	file_shortener_v2_proto_depIdxs = nil
}
